@startuml
'https://plantuml.com/sequence-diagram

autonumber

Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response success

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml